name: Build binary

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Gwm
        run : sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v7
        with:
          name: serial_usb
          path: build/
          retention-days: 1